/* The following code was generated by JFlex 1.6.1 */

package yal.analyse ;

import java_cup.runtime.*;
import yal.exceptions.AnalyseLexicaleException;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/marli/Documents/Fac/S6/Yal/compilation/src/yal/analyse/UnitesLexicales.jflex</tt>
 */
public class AnalyseurLexical implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\4\1\5\1\6\1\4\22\0\1\7\1\41\6\0"+
    "\1\42\1\43\1\34\1\35\1\0\1\36\1\0\1\3\12\2\1\0"+
    "\1\32\1\40\1\33\1\37\2\0\32\1\4\0\1\1\1\0\1\14"+
    "\1\20\1\31\1\17\1\16\1\23\1\13\1\1\1\24\2\1\1\30"+
    "\1\15\1\25\1\12\1\10\1\26\1\11\1\27\1\22\1\21\5\1"+
    "\12\0\1\5\u1fa2\0\1\5\1\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\13\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\1\16\1\0\2\2\1\17\1\2\1\20\7\2\1\21"+
    "\1\2\1\22\1\23\10\2\1\24\1\25\15\2\1\26"+
    "\2\2\1\27\2\2\1\30\3\2\1\31\1\32\2\2"+
    "\1\33\1\34\4\2\1\35\1\36\3\2\1\37\1\2"+
    "\1\40\1\2\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\44\0\264\0\330"+
    "\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8"+
    "\0\u021c\0\44\0\u0240\0\44\0\44\0\44\0\44\0\44"+
    "\0\u0264\0\44\0\44\0\u0288\0\u02ac\0\u02d0\0\110\0\u02f4"+
    "\0\110\0\u0318\0\u033c\0\u0360\0\u0384\0\u03a8\0\u03cc\0\u03f0"+
    "\0\u0414\0\u0438\0\44\0\44\0\u045c\0\u0480\0\u04a4\0\u04c8"+
    "\0\u04ec\0\u0510\0\u0534\0\u0558\0\u057c\0\110\0\u05a0\0\u05c4"+
    "\0\u05e8\0\u060c\0\u0630\0\u0654\0\u0678\0\u069c\0\u06c0\0\u06e4"+
    "\0\u0708\0\u072c\0\u0750\0\110\0\u0774\0\u0798\0\110\0\u07bc"+
    "\0\u07e0\0\110\0\u0804\0\u0828\0\u084c\0\110\0\110\0\u0870"+
    "\0\u0894\0\110\0\110\0\u08b8\0\u08dc\0\u0900\0\u0924\0\110"+
    "\0\110\0\u0948\0\u096c\0\u0990\0\110\0\u09b4\0\110\0\u09d8"+
    "\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\0\2\6\1\7"+
    "\1\10\1\11\1\3\1\12\1\3\1\13\1\14\2\3"+
    "\1\15\1\16\1\3\1\17\1\3\1\20\1\21\1\3"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\45\0\2\3\5\0\22\3\14\0\1\4"+
    "\44\0\1\34\41\0\2\3\5\0\1\3\1\35\20\3"+
    "\13\0\2\3\5\0\6\3\1\36\13\3\13\0\2\3"+
    "\5\0\11\3\1\37\10\3\13\0\2\3\5\0\20\3"+
    "\1\40\1\3\13\0\2\3\5\0\12\3\1\41\2\3"+
    "\1\42\3\3\1\43\13\0\2\3\5\0\6\3\1\44"+
    "\13\3\13\0\2\3\5\0\4\3\1\45\15\3\13\0"+
    "\2\3\5\0\2\3\1\46\11\3\1\47\5\3\13\0"+
    "\2\3\5\0\2\3\1\50\17\3\13\0\2\3\5\0"+
    "\14\3\1\51\5\3\13\0\2\3\5\0\14\3\1\52"+
    "\5\3\45\0\1\53\43\0\1\54\10\0\4\34\1\6"+
    "\2\0\35\34\1\0\2\3\5\0\2\3\1\55\17\3"+
    "\13\0\2\3\5\0\1\56\21\3\13\0\2\3\5\0"+
    "\2\3\1\57\17\3\13\0\2\3\5\0\12\3\1\60"+
    "\7\3\13\0\2\3\5\0\1\3\1\61\20\3\13\0"+
    "\2\3\5\0\10\3\1\62\11\3\13\0\2\3\5\0"+
    "\15\3\1\63\4\3\13\0\2\3\5\0\15\3\1\64"+
    "\4\3\13\0\2\3\5\0\15\3\1\65\4\3\13\0"+
    "\2\3\5\0\15\3\1\66\4\3\13\0\2\3\5\0"+
    "\15\3\1\67\4\3\13\0\2\3\5\0\1\3\1\70"+
    "\20\3\13\0\2\3\5\0\3\3\1\71\16\3\13\0"+
    "\2\3\5\0\6\3\1\72\13\3\13\0\2\3\5\0"+
    "\1\3\1\73\20\3\13\0\2\3\5\0\14\3\1\74"+
    "\5\3\13\0\2\3\5\0\14\3\1\75\5\3\13\0"+
    "\2\3\5\0\11\3\1\76\10\3\13\0\2\3\5\0"+
    "\12\3\1\77\7\3\13\0\2\3\5\0\21\3\1\100"+
    "\13\0\2\3\5\0\12\3\1\101\4\3\1\102\2\3"+
    "\13\0\2\3\5\0\2\3\1\103\17\3\13\0\2\3"+
    "\5\0\6\3\1\104\13\3\13\0\2\3\5\0\1\3"+
    "\1\105\20\3\13\0\2\3\5\0\12\3\1\106\7\3"+
    "\13\0\2\3\5\0\17\3\1\107\2\3\13\0\2\3"+
    "\5\0\6\3\1\110\13\3\13\0\2\3\5\0\1\3"+
    "\1\111\20\3\13\0\2\3\5\0\12\3\1\112\7\3"+
    "\13\0\2\3\5\0\16\3\1\113\3\3\13\0\2\3"+
    "\5\0\12\3\1\114\7\3\13\0\2\3\5\0\4\3"+
    "\1\115\15\3\13\0\2\3\5\0\14\3\1\116\5\3"+
    "\13\0\2\3\5\0\15\3\1\117\4\3\13\0\2\3"+
    "\5\0\4\3\1\120\15\3\13\0\2\3\5\0\6\3"+
    "\1\121\13\3\13\0\2\3\5\0\1\3\1\122\20\3"+
    "\13\0\2\3\5\0\6\3\1\123\13\3\13\0\2\3"+
    "\5\0\11\3\1\124\10\3\13\0\2\3\5\0\14\3"+
    "\1\125\5\3\13\0\2\3\5\0\15\3\1\126\4\3"+
    "\13\0\2\3\5\0\5\3\1\127\14\3\13\0\2\3"+
    "\5\0\1\3\1\130\20\3\13\0\2\3\5\0\6\3"+
    "\1\131\13\3\13\0\2\3\5\0\2\3\1\132\17\3"+
    "\13\0\2\3\5\0\12\3\1\133\7\3\13\0\2\3"+
    "\5\0\5\3\1\134\14\3\13\0\2\3\5\0\15\3"+
    "\1\135\4\3\13\0\2\3\5\0\16\3\1\136\3\3"+
    "\13\0\2\3\5\0\6\3\1\137\13\3\13\0\2\3"+
    "\5\0\11\3\1\140\10\3\13\0\2\3\5\0\6\3"+
    "\1\141\13\3\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2556];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\13\1\1\11\1\1\5\11"+
    "\1\1\2\11\1\0\16\1\2\11\65\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

  private StringBuilder chaine ;

  private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn) ;
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value) ;
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalyseurLexical(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {         return symbol(CodesLexicaux.EOF) ;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new AnalyseLexicaleException(yyline, yycolumn, yytext()) ;
            }
          case 34: break;
          case 2: 
            { return symbol(CodesLexicaux.IDF, yytext());
            }
          case 35: break;
          case 3: 
            { return symbol(CodesLexicaux.CSTENTIERE, yytext());
            }
          case 36: break;
          case 4: 
            { return symbol(CodesLexicaux.DIVISE);
            }
          case 37: break;
          case 5: 
            { 
            }
          case 38: break;
          case 6: 
            { return symbol(CodesLexicaux.POINTVIRGULE);
            }
          case 39: break;
          case 7: 
            { return symbol(CodesLexicaux.EGAL);
            }
          case 40: break;
          case 8: 
            { return symbol(CodesLexicaux.MULT);
            }
          case 41: break;
          case 9: 
            { return symbol(CodesLexicaux.PLUS);
            }
          case 42: break;
          case 10: 
            { return symbol(CodesLexicaux.MOINS);
            }
          case 43: break;
          case 11: 
            { return symbol(CodesLexicaux.SUP);
            }
          case 44: break;
          case 12: 
            { return symbol(CodesLexicaux.INF);
            }
          case 45: break;
          case 13: 
            { return symbol(CodesLexicaux.PAR_OUVRANTE);
            }
          case 46: break;
          case 14: 
            { return symbol(CodesLexicaux.PAR_FERMANTE);
            }
          case 47: break;
          case 15: 
            { return symbol(CodesLexicaux.OU);
            }
          case 48: break;
          case 16: 
            { return symbol(CodesLexicaux.ET);
            }
          case 49: break;
          case 17: 
            { return symbol(CodesLexicaux.SI);
            }
          case 50: break;
          case 18: 
            { return symbol(CodesLexicaux.EGALITE);
            }
          case 51: break;
          case 19: 
            { return symbol(CodesLexicaux.DIFFERENCE);
            }
          case 52: break;
          case 20: 
            { return symbol(CodesLexicaux.FIN);
            }
          case 53: break;
          case 21: 
            { return symbol(CodesLexicaux.NON);
            }
          case 54: break;
          case 22: 
            { return symbol(CodesLexicaux.LIRE);
            }
          case 55: break;
          case 23: 
            { return symbol(CodesLexicaux.ALORS);
            }
          case 56: break;
          case 24: 
            { return symbol(CodesLexicaux.DEBUT);
            }
          case 57: break;
          case 25: 
            { return symbol(CodesLexicaux.FINSI);
            }
          case 58: break;
          case 26: 
            { return symbol(CodesLexicaux.SINON);
            }
          case 59: break;
          case 27: 
            { return symbol(CodesLexicaux.ENTIER);
            }
          case 60: break;
          case 28: 
            { return symbol(CodesLexicaux.ECRIRE);
            }
          case 61: break;
          case 29: 
            { return symbol(CodesLexicaux.REPETER);
            }
          case 62: break;
          case 30: 
            { return symbol(CodesLexicaux.TANTQUE);
            }
          case 63: break;
          case 31: 
            { return symbol(CodesLexicaux.FONCTION);
            }
          case 64: break;
          case 32: 
            { return symbol(CodesLexicaux.PROGRAMME);
            }
          case 65: break;
          case 33: 
            { return symbol(CodesLexicaux.FINTANTQUE);
            }
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
