
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 15 18:05:35 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 8;
  public static final int DEBUT = 3;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int COMMENTAIRE = 7;
  public static final int error = 1;
  public static final int CSTENTIERE = 9;
}

