
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 06 14:24:42 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 20;
  public static final int PARFERMANTE = 19;
  public static final int EGAL = 9;
  public static final int CSTENTIERE = 21;
  public static final int LIRE = 7;
  public static final int ECRIRE = 6;
  public static final int TANTQUE = 14;
  public static final int ALORS = 11;
  public static final int OPERCALCNP = 23;
  public static final int REPETER = 15;
  public static final int NON = 17;
  public static final int MOINS = 24;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 16;
  public static final int OPERBOOLBB = 26;
  public static final int SINON = 12;
  public static final int OPERBOOLEB = 25;
  public static final int OPERCALCP = 22;
  public static final int ENTIER = 8;
  public static final int EOF = 0;
  public static final int PAROUVRANTE = 18;
  public static final int SI = 10;
  public static final int error = 1;
  public static final int DEBUT = 3;
  public static final int OPERBOOLRB = 27;
  public static final int FINSI = 13;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

